# Manifest for the swarm deployment
version: '3.7'

services:
  app:
    image: '${IMAGE}:${VERSION}'
    environment:
      - BASE_URL="https://${HOST}"
      - PORT=8090
      - DATABASE_URL
      - SESSION_SECRET
    networks:
      - traefik
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '512M'
        reservations:
          cpus: '0.05'
          memory: '128M'
      # TODO: we don't have workers yet
      # placement:
      #   constraints:
      #     - node.role == worker
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.services.clj-shorty.loadbalancer.server.port=8090'

        # HTTP
        - 'traefik.http.routers.clj-shorty.rule=Host(`${HOST}`)'
        - 'traefik.http.routers.clj-shorty.entrypoints=web'
        - 'traefik.http.routers.clj-shorty.middlewares=force-https@file'

        # HTTPS
        - 'traefik.http.routers.clj-shorty-secure.rule=Host(`${HOST}`)'
        - 'traefik.http.routers.clj-shorty-secure.middlewares=gzip@file'
        - 'traefik.http.routers.clj-shorty-secure.entrypoints=web-secure'
        - 'traefik.http.routers.clj-shorty-secure.tls=true'
        - 'traefik.http.routers.clj-shorty-secure.tls.certresolver=letsencrypt'
networks:
  traefik:
    external: true
