name: CD

on:
  push:
    branches:
      - master

env:
  IMAGE: 'docker.pkg.github.com/danielschleindlsperger/clj-shorty/app'

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          registry: rg.nl-ams.scw.cloud
          repository: petprojects/clj-shorty/app
          tags: 'latest,${{ steps.version.outputs.version }}'
      # TODO: this could be another job that depends on the build job but only runs on master
      - name: Deploy to CapRover
        uses: ./.github/actions/caprover-deploy
        with:
          caprover_url: 'https://caprover.lchthbr.xyz'
          password: ${{ secrets.CAPROVER_SECRET }}
          app_name: clj-shorty
          image_name: '${{ env.IMAGE }}:${{ steps.version.outputs.version }}'
