name: CD

on:
  push:
    branches:
      - master

env:
  IMAGE: 'docker.pkg.github.com/danielschleindlsperger/clj-shorty/clj-shorty'

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: danielschleindlsperger
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: danielschleindlsperger/clj-shorty/app
          tags: 'latest,${{ steps.version.outputs.version }}'
      # - name: Deploy container
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script_stop: true
      #     script: |
      #       docker run --restart-always -ti --network postgres ${{ IMAGE }}:${{ VERSION }}
