name: CD

on:
  push:
    branches:
      - master

env:
  IMAGE: 'docker.pkg.github.com/danielschleindlsperger/clj-shorty/app'

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: danielschleindlsperger
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: danielschleindlsperger/clj-shorty/app
          tags: 'latest,${{ steps.version.outputs.version }}'
      - name: Deploy to Docker swarm
        uses: ./.github/actions/docker-swarm-deploy
        with:
          username: danielschleindlsperger
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          remote_docker_host: root@164.90.215.22
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          stack_file: ./infrastrucuure/docker-compose.yml
          stack_name: clj-shorty
        env:
          VERSION: ${{ steps.version.outputs.version }}
          HOST: s.lchthbr.xyz
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
