name: CD

on: [push, pull_request]

env:
  REGISTRY: 'rg.nl-ams.scw.cloud'
  REPOSITORY: 'petprojects/clj-shorty/app'

jobs:
  build-and-push-container:
    name: Build and push container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit

      - name: Enable Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.4

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: nologin
          password: ${{ secrets.SCALEWAY_SECRET_KEY }}
          registry: ${{ env.REGISTRY }}
          repository: ${{ env.REPOSITORY }}
          tags: 'latest,${{ steps.version.outputs.version }}'

  # Deploy job only runs on master after containers are built successful
  migrate-and-deploy:
    name: Migrate database and deploy application
    runs-on: ubuntu-latest
    needs: build-and-push-container
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit

      - name: Migrate database
        uses: ./.github/actions/sqitch-migrate
        with:
          database_url: ${{ secrets.SQITCH_DATABASE_URL }}

      - name: Deploy to CapRover
        uses: ./.github/actions/caprover-deploy
        with:
          caprover_url: 'https://captain.lchthbr.xyz'
          password: ${{ secrets.CAPROVER_SECRET }}
          app_name: clj-shorty
          image_name: '${{ env.REGISTRY }}/${{ env.REPOSITORY}}:${{ steps.version.outputs.version }}'
