name: CD

on:
  push:
    branches:
      - master

env:
  IMAGE: 'docker.pkg.github.com/danielschleindlsperger/clj-shorty/clj-shorty'

jobs:
  build-and-push-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1
      - name: Determine version
        id: version
        uses: ./.github/actions/version-commit
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: danielschleindlsperger
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: danielschleindlsperger/clj-shorty/app
          tags: 'latest,${{ steps.version.outputs.version }}'
      - name: Deploy to Docker swarm
        uses: wshihadeh/docker-deployment-action@master
        with:
          # TODO: assign hostname to manager nodes
          remote_docker_host: root@164.90.215.22
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          deployment_mode: docker-swarm
          deploy_path: ./infrastructure
          stack_file_name: docker-compose.yml
          args: clj-shorty
        env:
          HOST: s.lchthbr.xyz
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
